apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
    - host: cheatsheet.dev
      http:
        paths:
          - path: /user/?(.*)
            backend:
              serviceName: auth-srv
              servicePort: 3000
          - path: /post/?(.*)
            backend:
              serviceName: post-srv
              servicePort: 3000
          - path: /?(.*)
            backend:
              serviceName: client-srv
              servicePort: 3000